behaviors:
  MoveToTarget:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 1.0e-5
      batch_size: 1024
      buffer_size: 10240
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 4800000
    time_horizon: 64
    summary_freq: 10000