behaviors:
  MoveToTarget:
    trainer_type: ppo
    max_steps: 5000000
    time_horizon: 256
    summary_freq: 20000
    keep_checkpoints: 10     #número de checkpoints gerados (cerebros .onnx intermediarios)
    checkpoint_interval: 500000
    # even_checkpoints: true
    hyperparameters:
      learning_rate: 1.0e-4
      batch_size: 1024
      buffer_size: 10240
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0