behaviors:
  MoveToTarget:
    trainer_type: sac
    max_steps: 9600000  # 4.8M é equivalente ao máximo de 4000 eps (1200 steps no máx.)
    time_horizon: 64
    summary_freq: 60000
    keep_checkpoints: 16     #número de checkpoints gerados (cerebros .onnx intermediarios)
    checkpoint_interval: 600000
    hyperparameters:
      learning_rate: 1.0e-5
      batch_size: 128
      buffer_size: 1200000
      learning_rate_schedule: constant
      buffer_init_steps: 5500
      init_entcoef: 0.75
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0